import Foundation

enum AppleClientDesign {
    static let css = #"""
    :root{--sb-bg:#f4f6f9;--sb-surface:#fff;--sb-text:#17212d;--sb-muted:#7b8796;--sb-line:#e8edf3;--sb-accent:#334155;--sb-soft:#edf2f7;--sb-radius:24px}
    html{font-optical-sizing:auto;-webkit-text-size-adjust:100%;background:var(--sb-bg)}
    body{background:var(--sb-bg)!important;color:var(--sb-text)!important;font-family:-apple-system,BlinkMacSystemFont,sans-serif!important;line-height:1.6}
    .wrap,.home-shell,.forum-layout,.forum-main,.main-panel,.forum-enhancements-shell{background:transparent!important}
    .main-panel{padding:12px 18px 24px!important}
    #sb-client-shell{position:relative!important;inset:auto!important;padding-top:0!important;background:var(--sb-bg)!important;backdrop-filter:none;box-shadow:none!important}
    .sb-client-title{min-height:52px!important;padding:0 18px!important;gap:12px;color:var(--sb-text)!important}
    .sb-client-title strong{font-size:19px!important;font-weight:720;letter-spacing:-.018em}
    .sb-client-title svg{width:20px!important;height:20px!important;display:block}
    .sb-client-title a,.sb-client-title button{width:40px!important;min-width:40px!important;min-height:40px!important;height:40px!important;border-radius:50%;color:var(--sb-accent)!important;background:var(--sb-surface)!important;border:1px solid var(--sb-line)!important}
    html[data-sb-view=home] .sb-client-title button{visibility:hidden}
    html:not([data-sb-view=home]) .sb-client-links,html:not([data-sb-view=home]) .sb-client-tools{display:none!important}
    .sb-client-links{display:grid!important;grid-template-columns:repeat(5,minmax(0,1fr));gap:6px!important;padding:2px 18px 10px!important;overflow:visible!important}
    .sb-client-links a{display:grid!important;place-items:center;min-height:33px;font-size:11px;white-space:nowrap;color:var(--sb-accent)!important;background:var(--sb-surface);border:1px solid var(--sb-line);border-radius:12px;text-decoration:none}
    .sb-client-tools{padding:0 18px 12px!important;gap:8px!important;align-items:center}
    .sb-client-search{display:flex;align-items:center;gap:9px;min-height:42px;border-radius:15px!important;padding:10px 13px!important;color:var(--sb-muted)!important;background:var(--sb-surface)!important;border:1px solid var(--sb-line);font-size:14px!important}
    .sb-client-search svg{width:17px;height:17px;flex:none}.sb-client-theme{display:grid;place-items:center;width:42px;height:42px;border-radius:15px;background:var(--sb-surface);border:1px solid var(--sb-line);padding:0!important}.sb-client-theme svg{width:20px;height:20px}
    #sb-client-tabs{left:14px!important;right:14px!important;bottom:calc(10px + env(safe-area-inset-bottom))!important;min-height:64px;padding:8px 4px!important;border-radius:25px!important;border:1px solid rgba(226,232,240,.8);background:rgba(255,255,255,.94)!important;box-shadow:0 7px 28px #17212d0c!important;backdrop-filter:blur(24px) saturate(150%);gap:3px}
    #sb-client-tabs a{min-width:0!important;flex:1;min-height:46px;border-radius:18px;padding:5px 4px;color:var(--sb-muted)!important;font-size:10px!important;gap:4px!important}
    #sb-client-tabs a.active{background:var(--sb-soft);color:var(--sb-accent)!important;font-weight:650}#sb-client-tabs svg{width:22px!important;height:22px!important}
    #sb-client-tabs.sb-topic-actions{padding:9px 12px!important}.sb-reply-open{background:var(--sb-soft)!important;border-radius:18px!important;min-height:43px!important}.sb-show-replies{font-size:13px!important;padding-inline:10px}
    .sb-home-intro{padding:12px 18px 10px}.sb-home-intro h1{font-size:24px;font-weight:760;letter-spacing:-.025em;line-height:1.25;margin:0;color:var(--sb-text)}
    .sb-client-filters{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr));gap:6px!important;padding:4px 18px 12px!important;overflow:visible!important}
    .sb-client-filters a,.sb-client-filters a:first-child,.sb-client-filters a:last-child{display:grid;place-items:center;min-height:37px!important;padding:6px 4px!important;border:1px solid var(--sb-line)!important;border-radius:12px!important;margin:0!important;background:var(--sb-surface);font-size:12px!important;color:var(--sb-muted)!important}
    .sb-client-filters a.active{background:var(--sb-accent)!important;border-color:var(--sb-accent)!important;color:white!important;box-shadow:0 3px 9px #33415517}
    .main-panel>.post-list{margin:0!important;padding:0!important}
    .main-panel>.post-list>.post-item:not(.post-entry){background:var(--sb-surface)!important;border:1px solid var(--sb-line)!important;box-shadow:0 2px 7px #17212d03!important;border-radius:21px!important;margin:0 0 10px!important;padding:16px!important}
    .post-title{font-size:16px!important;line-height:1.55!important;font-weight:650!important;letter-spacing:-.005em}
    .post-meta{font-size:11px!important;line-height:1.6!important;color:var(--sb-muted)!important}.post-meta a{color:inherit}
    .post-title-row{gap:6px!important;align-items:flex-start!important;flex-wrap:wrap!important}
    .topic-badge,.topic-stamp-badge,.red-packet-title-status{font-size:10px!important;line-height:1.5!important;border-radius:7px!important;padding:2px 6px!important}
    .post-avatar{flex-shrink:0!important}.avatar-profile-link{border-radius:50%!important;background:transparent!important}.post-avatar img.avatar-img{aspect-ratio:1/1;border-radius:50%!important;object-fit:cover;object-position:center}
    html[data-sb-view=topic] .main-panel{padding:0!important}.post-topic-title{padding:20px 22px 22px!important}.post-content-title{font-size:25px!important;line-height:1.4!important;font-weight:750!important;letter-spacing:-.025em!important;color:var(--sb-text)}.post-content-stats{font-size:12px!important;color:var(--sb-muted)!important}
    .topic-post-list>.post-entry{margin:0 18px 14px!important;border:1px solid var(--sb-line)!important;border-radius:24px!important;background:var(--sb-surface)!important;padding:20px 18px!important;box-shadow:none!important}
    .topic-post-list>.post-entry>.post-avatar{top:20px!important;left:18px!important}
    .topic-post-list .post-head .post-author{font-size:16px!important;font-weight:720!important;flex-basis:100%!important;line-height:1.45}
    .topic-post-list .post-user-group,.topic-post-list .gacha-title-badge,.topic-post-list .topic-op-badge{font-size:10px!important;line-height:1.4!important;min-width:0!important;max-width:100%!important;white-space:normal!important;overflow-wrap:anywhere;padding:2px 5px!important;border-radius:6px!important}
    .topic-post-list .post-content{font-size:16px!important;line-height:1.85!important;margin:17px 0!important;color:var(--sb-text)}.topic-post-list .post-meta{font-size:11px!important;gap:7px!important}
    .topic-post-list .post-entry.quote-threads-thread-item:not(.quote-threads-child){margin-bottom:0!important;border-bottom:0!important;border-radius:24px 24px 0 0!important}
    .topic-post-list .post-entry.quote-threads-child{margin-top:0!important;margin-bottom:0!important;border-top:1px solid var(--sb-line)!important;border-bottom:0!important;border-radius:0!important;background:var(--sb-surface)!important;padding-left:27px!important}
    .topic-post-list .post-entry.quote-threads-child>.post-avatar{left:27px!important;width:36px!important}.quote-threads-child>.post-avatar img{width:36px!important;height:36px!important}
    .topic-post-list .post-entry.quote-threads-thread-end{border-radius:0 0 24px 24px!important;border-bottom:1px solid var(--sb-line)!important;margin-bottom:14px!important}
    .topic-post-list .post-entry.quote-threads-cross-page{border-radius:24px!important;border:1px solid var(--sb-line)!important;margin-bottom:14px!important}
    .topic-post-list .post-avatar,.topic-post-list .avatar-profile-link{width:42px!important;height:42px!important;min-height:42px!important;max-height:42px!important;overflow:visible!important;display:block!important}
    .topic-post-list .post-avatar img{width:42px!important;height:42px!important;min-width:42px!important;max-width:42px!important;border-radius:50%!important;object-fit:cover!important;clip-path:circle(50%)!important}
    .topic-post-list .quote-threads-child .post-avatar,.topic-post-list .quote-threads-child .avatar-profile-link,.topic-post-list .quote-threads-child .post-avatar img{width:36px!important;height:36px!important;min-width:36px!important;max-width:36px!important;min-height:36px!important;max-height:36px!important}
    .topic-post-list .post-entry.quote-threads-is-collapsed{display:none!important}
    .topic-post-list .post-entry:has(+.quote-threads-toggle-row){border-bottom:0!important;border-radius:0!important;margin-bottom:0!important}
    .quote-threads-toggle-row{list-style:none;background:var(--sb-surface);border:1px solid var(--sb-line);border-top:0;border-radius:0 0 24px 24px;margin:0 18px 14px;padding:0 18px 14px}
    .quote-threads-toggle{border:0!important;background:var(--sb-soft)!important;color:var(--sb-accent)!important;font-size:12px!important;min-height:36px!important;border-radius:12px!important;padding:8px 12px!important}
    .quote-threads-reference{color:var(--sb-accent)!important;background:var(--sb-soft);border-radius:6px;padding:2px 6px;font-size:10px}
    .sb-replies-heading{padding:12px 22px 17px!important;border:0!important;font-size:18px!important;font-weight:720!important;color:var(--sb-text)}
    .post-content img{border-radius:14px!important}.post-content pre{background:var(--sb-soft)!important;border-radius:14px!important}.post-content blockquote{border-color:#94a3b8!important;border-radius:0 12px 12px 0}
    .topic-post-list .post-signature,.topic-post-list .post-signature-content{font-size:11px!important;line-height:1.6!important;color:var(--sb-muted)!important}.topic-post-list .post-signature button,.topic-post-list .post-signature form button[type=submit]{background:transparent!important;border:0!important;color:var(--sb-muted)!important;font-size:11px!important;min-height:30px!important;padding:3px 0!important}
    #client-search-shell{padding:10px 0 20px!important}html[data-sb-view=search] .main-panel{padding:14px 20px 22px!important}.client-search-tabs{background:none!important;margin:0 0 15px!important;padding:0!important}.client-search-tabs button{font-size:12px!important;background:var(--sb-soft)!important;color:var(--sb-accent)!important;border-radius:10px!important;box-shadow:none!important;min-height:30px!important;flex:0 0 auto!important;padding:4px 12px!important}
    #client-search-shell input[type=text],#client-search-shell input[type=search]{background:var(--sb-surface)!important;border:1px solid var(--sb-line)!important;border-radius:17px!important;min-height:48px!important;font-size:16px!important;padding:12px 14px!important}
    #client-search-shell button[type=submit]{background:var(--sb-accent)!important;color:white!important;border-radius:15px!important;padding-inline:15px!important;font-size:14px!important}
    .client-history-head{font-size:17px!important;margin-top:26px!important;color:var(--sb-text)}.client-history-head button{font-size:13px!important;color:var(--sb-muted)!important}.client-history-row{padding:10px 0!important;border-color:var(--sb-line)!important}.client-history-row .term{font-size:15px!important}.client-search-note{font-size:12px!important;color:var(--sb-muted)!important}
    #sb-client-panel{padding:18px!important}.sb-client-profile{padding:20px 18px!important;background:var(--sb-surface);border:1px solid var(--sb-line);border-radius:25px;margin-bottom:14px}.sb-client-profile img{width:66px!important;height:66px!important;min-width:66px!important;max-width:66px!important;object-fit:cover!important;border-radius:50%!important}.sb-client-profile-name{font-size:24px!important;font-weight:750;letter-spacing:-.02em;color:var(--sb-text)!important}.sb-client-profile-uid{font-size:11px!important;color:var(--sb-muted)!important}.sb-client-profile-details .user-rank{font-size:12px!important}.sb-client-profile-details .gacha-title-badge{font-size:11px!important;line-height:1.5}.sb-client-edit-profile{border-radius:14px!important;background:var(--sb-soft)!important;color:var(--sb-accent)!important;font-size:13px!important;padding:11px!important;margin-top:18px!important}
    .sb-client-account-links{border:1px solid var(--sb-line);border-radius:24px!important;background:var(--sb-surface)!important;padding:0 18px!important;margin-top:0!important}.sb-client-account-links a{min-height:53px!important;font-size:14px!important;color:var(--sb-text)!important;border-color:var(--sb-line)!important}
    .sb-client-category-grid{gap:12px!important}.sb-client-category-grid a{background:var(--sb-surface)!important;border:1px solid var(--sb-line);border-radius:23px!important;color:var(--sb-text)!important;min-height:86px;padding:20px 16px!important;display:flex;align-items:center;font-size:15px!important;font-weight:650}
    html[data-sb-view=messages] .post-item,html[data-sb-view=messages] .post-item.post-entry{margin-bottom:10px!important;padding:16px!important;border:1px solid var(--sb-line)!important;border-radius:21px!important;background:var(--sb-surface)!important}.notification-item,.notify-item,.direct-message-item{background:var(--sb-surface)!important;border:1px solid var(--sb-line)!important;border-radius:20px!important;margin-bottom:10px;padding:16px!important}.notification-item a,.notify-item a,.direct-message-item a{font-size:14px!important}.direct-messages-compose,.reply-panel,.bio-card,.user-card{border-radius:20px!important}
    html[data-sb-view=messages] .post-avatar img,html[data-sb-view=messages] .avatar-profile-link img{width:42px!important;height:42px!important;min-width:42px!important;min-height:42px!important;max-width:42px!important;max-height:42px!important;border-radius:50%!important;object-fit:cover!important;object-position:center!important;clip-path:circle(50%)!important}
    .main-panel .card:not(.post-entry),.main-panel .panel{border:1px solid var(--sb-line)!important;border-radius:22px!important;background:var(--sb-surface)!important;padding:18px!important;box-shadow:none!important;margin-block:12px!important}
    .main-panel form input[type=text],.main-panel form input[type=email],.main-panel form input[type=password],.main-panel form input[type=search],.main-panel textarea,.main-panel select{border:1px solid var(--sb-line)!important;border-radius:14px!important;background:var(--sb-surface)!important;color:var(--sb-text)!important;min-height:44px;padding:10px 12px!important}
    .main-panel form button[type=submit],.main-panel input[type=submit]{border-radius:14px!important;background:var(--sb-accent)!important;border-color:var(--sb-accent)!important;color:white!important;min-height:44px;font-size:14px}
    .main-panel h1,.main-panel h2{letter-spacing:-.02em;line-height:1.4;color:var(--sb-text)}.main-panel .profile-toolbar{display:flex;flex-wrap:wrap!important;gap:6px!important;overflow:visible!important;padding:0 0 16px!important}.profile-toolbar a{font-size:12px!important;min-height:34px!important;padding:7px 11px!important;background:var(--sb-surface);border:1px solid var(--sb-line)!important;border-radius:11px!important;color:var(--sb-muted)!important}.profile-toolbar a.active{background:var(--sb-accent);color:var(--sb-surface)!important}
    .main-panel table{max-width:100%;overflow-x:auto;border-collapse:separate;border-spacing:0;border:1px solid var(--sb-line);border-radius:17px;background:var(--sb-surface)}.main-panel th,.main-panel td{padding:10px 12px;font-size:13px;border-color:var(--sb-line)}.main-panel th{color:var(--sb-muted);font-weight:600;background:var(--sb-soft)}
    .modal-panel,.color-scheme-modal-dialog{background:var(--sb-surface)!important;border:1px solid var(--sb-line)!important;border-radius:26px!important;box-shadow:0 20px 70px #17212d25!important;max-width:calc(100vw - 28px)!important}.modal-head{padding:17px 18px!important;border-color:var(--sb-line)!important}.modal-body{padding:18px!important}.modal-head strong{font-size:17px!important}.main-panel form button.danger[type=submit]{background:#dc4545!important;border-color:#dc4545!important;color:white!important}.main-panel form button.alt[type=submit]{background:var(--sb-soft)!important;color:var(--sb-accent)!important;border-color:var(--sb-line)!important}
    #sb-reply-sheet{background:var(--sb-surface)!important;border-radius:29px 29px 0 0!important;box-shadow:0 -12px 50px #17212d1c!important}.sb-reply-grab::after{background:#c6cfd9!important}.sb-reply-heading{padding-bottom:9px!important}.sb-reply-heading strong{font-size:17px!important;font-weight:700}.sb-reply-content textarea{background:var(--sb-bg)!important;border-radius:17px!important;border:1px solid var(--sb-line)!important;min-height:112px!important}.sb-reply-content .quick-reply-actions{padding-top:8px}
    html[data-sb-view=search] #client-search-shell{padding:8px 0 20px!important;background:transparent!important}
    #client-search-shell .client-search-tabs{display:none!important}
    #client-search-shell form.client-search-form{display:flex!important;flex-wrap:nowrap!important;gap:8px!important;padding:8px!important;background:var(--sb-surface)!important;border:1px solid var(--sb-line)!important;border-radius:22px!important;align-items:center!important}
    #client-search-shell form.client-search-form input[type=text],#client-search-shell form.client-search-form input[type=search]{background:transparent!important;border:0!important;border-radius:0!important;min-height:44px!important;font-size:16px!important;padding:8px 10px!important;min-width:0!important;flex:1!important;width:0!important}
    #client-search-shell form.client-search-form button[type=submit]{flex:none!important;min-height:44px!important;padding:10px 16px!important;border-radius:15px!important;font-size:14px!important}
    #client-search-shell .client-search-history{margin-top:18px;padding:18px;background:var(--sb-surface);border:1px solid var(--sb-line);border-radius:24px}
    #client-search-shell .client-history-head{margin:0 0 12px!important;font-size:17px!important;line-height:1.5!important}.client-history-head button{font-size:13px!important;min-height:32px;color:var(--sb-muted)!important}
    #client-search-shell .client-search-note{padding:16px 0!important;margin:0!important;text-align:center;font-size:13px!important;color:var(--sb-muted)!important}
    #client-search-shell .client-history-row{padding:11px 0!important;font-size:14px!important}.client-history-row:last-child{border-bottom:0!important}
    .main-panel .reply-pin-action-form button.reply-pin-action-button{background:transparent!important;border:0!important;box-shadow:none!important;color:var(--sb-muted)!important;min-height:32px!important;min-width:32px!important;padding:0!important;border-radius:0!important;opacity:1!important}
    .topic-post-list>.post-entry{position:relative!important;top:auto!important;bottom:auto!important;transform:none!important}
    .topic-post-list .post-entry button,.topic-post-list .post-entry a.btn,.topic-post-list .post-entry input[type=submit]{background:transparent!important;background-image:none!important;border:0!important;box-shadow:none!important;color:var(--sb-muted)!important}
    .topic-post-list .post-entry button:hover,.topic-post-list .post-entry button:active,.topic-post-list .post-entry a.btn:hover,.topic-post-list .post-entry a.btn:active{background:transparent!important;box-shadow:none!important}
    .topic-post-list .post-head,.topic-post-list .post-meta,.topic-post-list .post-ops,.topic-post-list .post-content,.topic-post-list .post-signature{position:static!important;inset:auto!important;transform:none!important}
    button,a{touch-action:manipulation}button:active,.sb-client-links a:active,.sb-client-filters a:active,.sb-client-account-links a:active{filter:brightness(.97);transform:scale(.985)}:focus-visible{outline:2px solid #64748b;outline-offset:3px}
    @media(prefers-color-scheme:dark){:root{--sb-bg:#101720;--sb-surface:#19222f;--sb-text:#eef2f7;--sb-muted:#99a6b6;--sb-line:#273447;--sb-accent:#bfd0e3;--sb-soft:#273447}#sb-client-shell{background:rgba(16,23,32,.94)!important}#sb-client-tabs{background:rgba(25,34,47,.96)!important;border-color:var(--sb-line)}.sb-client-filters a.active{color:#19222f!important}}
    @media(prefers-reduced-transparency:reduce){#sb-client-shell,#sb-client-tabs{background:var(--sb-surface)!important;backdrop-filter:none}}
    @media(prefers-reduced-motion:reduce){button:active,a:active{transform:none!important}*{scroll-behavior:auto!important}}
    @media(prefers-contrast:more){:root{--sb-muted:#475569;--sb-line:#94a3b8}#sb-client-tabs{border:1px solid #64748b}}
    """#
    static var script: String {
        let literal = String(decoding: try! JSONSerialization.data(withJSONObject: [css]), as: UTF8.self)
        return #"""
        (()=>{
          if(location.hostname!=='linux.sb'||document.getElementById('sb-apple-client-design'))return;
          const css=document.createElement('style');css.id='sb-apple-client-design';css.textContent=LITERAL[0];document.head.append(css);
          const view=()=>location.hash==='#client-my'?'profile':location.hash==='#client-categories'?'categories':/^\/topic\/\d+/.test(location.pathname)?'topic':location.pathname==='/search'?'search':new URLSearchParams(location.search).get('tab')==='notifications'?'messages':location.pathname==='/login'?'login':(location.pathname==='/'||location.pathname==='/index.php'||location.pathname==='/topic_featured'||/^\/forum\/\d+/.test(location.pathname))?'home':'page';
          const applyView=()=>{document.documentElement.dataset.sbView=view();const title=document.querySelector('#sb-client-shell strong');if(title){const names={profile:'我的',categories:'分类',topic:'话题',search:'搜索',messages:'消息',login:'登录',home:'LINUX SB'};title.textContent=names[view()]||document.title.split(' - ')[0]||'社区'}};applyView();window.addEventListener('hashchange',applyView);
          const loadingStyle=document.createElement('style');loadingStyle.textContent=`#sb-route-loading{position:fixed;inset:0;z-index:205;background:var(--sb-bg);padding:20px 18px;overflow:auto;color:var(--sb-text)}#sb-route-loading header{display:flex;align-items:center;gap:16px;margin-bottom:28px}#sb-route-loading button{border:0;background:var(--sb-surface);color:var(--sb-muted);border-radius:50%;width:44px;height:44px;font:inherit;font-size:24px}#sb-route-loading h1{margin:0;font-size:21px}#sb-route-loading p{font-size:13px;color:var(--sb-muted)}.sb-loading-card{padding:22px;background:var(--sb-surface);border:1px solid var(--sb-line);border-radius:24px;margin-bottom:14px}.sb-loading-line{height:14px;border-radius:8px;background:var(--sb-soft);margin:14px 0;animation:sb-loading-pulse 1.1s ease-in-out infinite alternate}.sb-loading-line:first-child{width:68%;height:20px}.sb-loading-line:last-child{width:42%}@keyframes sb-loading-pulse{to{opacity:.4}}@media(prefers-reduced-motion:reduce){.sb-loading-line{animation:none}}`;document.head.append(loadingStyle);
          let loadingTimer;const clearLoading=()=>{clearTimeout(loadingTimer);document.getElementById('sb-route-loading')?.remove()};
          window.sbShowRouteLoading=(href,label)=>{const url=new URL(href,location.href);if(url.origin!==location.origin||url.href===location.href||(url.pathname===location.pathname&&url.search===location.search&&url.hash))return;clearLoading();const overlay=document.createElement('section');overlay.id='sb-route-loading';overlay.setAttribute('role','status');overlay.setAttribute('aria-live','polite');const header=document.createElement('header');const cancel=document.createElement('button');cancel.textContent='‹';cancel.setAttribute('aria-label','取消加载');cancel.onclick=()=>{window.stop();clearLoading()};const heading=document.createElement('h1');heading.textContent=label||(/^\/topic\/\d+/.test(url.pathname)?'话题':url.pathname==='/search'?'搜索':url.search.includes('tab=notifications')?'消息':'社区');header.append(cancel,heading);overlay.append(header);const status=document.createElement('p');status.textContent='正在加载内容…';overlay.append(status);for(let i=0;i<3;i++){const card=document.createElement('div');card.className='sb-loading-card';for(let j=0;j<3;j++){const line=document.createElement('div');line.className='sb-loading-line';card.append(line)}overlay.append(card)}document.body.append(overlay);loadingTimer=setTimeout(()=>{status.textContent='连接较慢，请稍候；也可以点左上角返回。'},12000)};
          document.addEventListener('click',event=>{if(event.defaultPrevented||event.metaKey||event.ctrlKey)return;const link=event.target.closest('a[href]');if(!link||link.hasAttribute('download')||link.target==='_blank'||link.closest('.post-ops')||link.classList.contains('quote-reply')||link.matches('[data-donate-btn],[data-donate-reaction]')||link.closest('.donate-modal,[data-donate-area]'))return;const url=new URL(link.href,location.href);if(url.origin!==location.origin)return;const label=link.closest('#sb-client-tabs,.sb-client-links,.sb-client-filters')?link.textContent.trim():undefined;if(label){window.sbShowRouteLoading(url.href,label);return}setTimeout(()=>{if(!event.defaultPrevented)window.sbShowRouteLoading(url.href,/^\/user\/\d+\/?$/.test(url.pathname)?'用户主页':undefined)},0)},true);
          window.addEventListener('pageshow',clearLoading);
          // Forge uses synchronous browser confirm(); use an HTML confirmation before submission.
          let forgeApproved=null;
          document.addEventListener('submit',event=>{const form=event.target;const button=form.querySelector?.('[data-gacha-forge-button]');if(!button||forgeApproved===form)return;event.preventDefault();event.stopImmediatePropagation();if(document.getElementById('sb-forge-confirm'))return;const count=Math.max(0,Number(form.querySelector('[data-gacha-forge-count]')?.value||0));if(count<1)return;const cost=Number(button.dataset.gachaForgeCost||0);const dialog=document.createElement('div');dialog.id='sb-forge-confirm';dialog.style.cssText='position:fixed;inset:0;z-index:240;background:#17212d66;display:grid;place-items:center;padding:24px';const card=document.createElement('section');card.setAttribute('role','dialog');card.setAttribute('aria-modal','true');card.style.cssText='background:var(--sb-surface);color:var(--sb-text);border-radius:26px;padding:24px;width:100%;max-width:380px';const title=document.createElement('h2');title.textContent='确认熔炼';const description=document.createElement('p');description.textContent='消耗 '+count*cost+' 个 '+(button.dataset.gachaForgeSource||'材料')+'，产生 '+count+' 个 '+(button.dataset.gachaForgeTarget||'称号')+'。此操作提交后可能无法撤销。';const actions=document.createElement('div');actions.style.cssText='display:flex;gap:12px;margin-top:22px';const cancel=document.createElement('button');cancel.type='button';cancel.textContent='取消';const submit=document.createElement('button');submit.type='button';submit.textContent='确认熔炼';for(const item of [cancel,submit])item.style.cssText='flex:1;min-height:44px;border:0;border-radius:14px;background:var(--sb-soft);color:var(--sb-text)';submit.style.background='#334155';submit.style.color='white';const prior=document.activeElement;const close=()=>{dialog.remove();prior?.focus()};cancel.onclick=close;dialog.onclick=e=>{if(e.target===dialog)close()};dialog.onkeydown=e=>{if(e.key==='Escape')close()};submit.onclick=()=>{close();const handler=form.onsubmit;forgeApproved=form;try{form.onsubmit=null;form.requestSubmit(event.submitter||button)}finally{form.onsubmit=handler;forgeApproved=null}};actions.append(cancel,submit);card.append(title,description,actions);dialog.append(card);document.body.append(dialog);cancel.focus()},true);
          const svg=(path)=>'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="'+path+'"/></svg>';
          const search=document.querySelector('.sb-client-search');if(search){search.replaceChildren();const icon=document.createElement('span');icon.innerHTML=svg('M15 15l5 5 M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0');const text=document.createElement('span');text.textContent='搜索社区';search.append(icon,text)}
          const theme=document.querySelector('.sb-client-theme');if(theme)theme.innerHTML=svg('M12 2v2 M12 20v2 M2 12h2 M20 12h2 M5 5l1.4 1.4 M17.6 17.6 19 19 M5 19l1.4-1.4 M17.6 6.4 19 5 M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0');
          const compose=document.querySelector('.sb-client-title a[href="/topic_edit"]');if(compose)compose.innerHTML=svg('M14 5l5 5 M4 20l4-1 12-12-3-3L5 16l-1 4 M13 20h7');
          if(view()==='home'){const filters=document.querySelector('.sb-client-filters');if(filters&&!document.querySelector('.sb-home-intro')){const intro=document.createElement('div');intro.className='sb-home-intro';intro.innerHTML='<h1>社区动态</h1>';filters.before(intro)}}
        })();
        """#.replacingOccurrences(of: "LITERAL", with: literal)
    }
}
